### PR TITLE
adding charles, Jimmy is a dingus

### PR DESCRIPTION
**Pull request by SeanGraney**

### CODE REVIEW

**Review by DanielFallon — APPROVED** [review]
accurate, jimmy is a dingus. I approve of this.

**Comment by DanielFallon** [comment]
side note, where did this github pages shit come from? there's no actions defined in the repo and pages are disabled... why did this bot even run?

**Comment by DanielFallon** [comment]
Found this discussion and the accompanying blog post, but neither development nor production were even enabled for github pages, so why did the bot trigger?

https://github.community/t/github-pages-bot-added-to-our-repos-unannounced/218214
https://github.blog/changelog/2021-12-16-github-pages-using-github-actions-for-builds-and-deployments-for-public-repositories/

**Comment by SeanGraney** [comment]
I was testing some things and enabled, then disabled github pages. Did I trigger something?

**Comment by DanielFallon** [comment]
oooh! yeah, it just kicked off a build (see the actions tab and the "error being deployed")

**Pull request merged**
